name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Which part of the version to bump'
        type: choice
        options: [patch, minor, major]
        default: patch

permissions:
  contents: write

jobs:
  release:
    uses: kodamity/.github/.github/workflows/release.yml@main
    with:
      bump: ${{ inputs.bump }}
